version: '3'

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  urlshortener:
    image: urlshortener
    build: .
    container_name: urlshortener
    ports:
      - "8080:8080"
    environment:
      REDIS_ADDRESS: redis:6379
      DOMAIN: localhost:8080
